<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MegaMicro</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MegaMicro.Windows.Core\MegaMicro.Windows.Core.csproj" />
  </ItemGroup>
</Project>
